### ISSUE TITLE
Get site working from DNS: rattlesnakeramble.org 

### ISSUE THREAD

**Issue by billwright** [billwright/rattlesnake_ramble#10]
This only works for www.rattlesnakeramble.org now.

**Comment by moveson** [comment]
Looks to me like this is working fine. Should this issue be closed?

**Comment by moveson** [comment]
May be addressed by #68

**Comment by moveson** [comment]
This is still not working after merging #68. Failure message is:
```
Domain                     Status       Reason                            Last Updated
─────────────────────────  ───────────  ────────────────────────────────  ────────────
rattlesnakeramble.org      Failing      DNS redirect not forwarding path  1 minute
www.rattlesnakeramble.org  Cert issued                                    14 days
```

**Comment by moveson** [comment]
Looks like `rattlesnakeramble.org` is hosted by Gandi.net. That site provides this information about DNS forwarding: https://docs.gandi.net/en/domain_names/common_operations/web_forwarding.html

**Comment by moveson** [comment]
Closing this issue because rattlesnakeramble.org is redirecting correctly to www.rattlesnakeramble.org.
